# Generated by Django 5.0.7 on 2024-07-24 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_empresa_delete_empresas'),
        ('frotas', '0001_initial'),
        ('situacoes', '0001_initial'),
        ('tipos_veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=80)),
                ('placas', models.CharField(max_length=80)),
                ('datacompra', models.DateField(db_column='dataCompra')),
                ('tipo_aquisicao', models.CharField(max_length=50)),
                ('km_inicial', models.IntegerField()),
                ('fk_empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa')),
                ('fk_frota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frotas.frota')),
                ('fk_situacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='situacoes.situacao')),
                ('fk_tipo_veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipos_veiculos.tipoveiculo')),
            ],
        ),
    ]
