# Generated by Django 5.0.7 on 2024-07-24 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cidades', '0001_initial'),
        ('estados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(db_column='CPF', max_length=50)),
                ('pis', models.CharField(db_column='PIS', max_length=30)),
                ('data_admissao', models.DateField()),
                ('data_demissao', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=90)),
                ('funcao', models.CharField(max_length=60)),
                ('telefone', models.CharField(max_length=60)),
                ('fk_cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cidades.cidade')),
                ('fk_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estados.estado')),
            ],
        ),
    ]
