# Generated by Django 5.0.7 on 2024-07-24 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_empresa_delete_empresas'),
        ('situacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_frota', models.CharField(max_length=20)),
                ('fk_empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa')),
                ('fk_situacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='situacoes.situacao')),
            ],
        ),
    ]
