# Generated by Django 5.0.7 on 2024-07-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da empresa', max_length=90)),
                ('cnpj', models.CharField(db_column='CNPJ', max_length=80)),
                ('ie', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('endereco', models.CharField(max_length=100)),
                ('fone', models.CharField(max_length=30)),
                ('responsavel', models.CharField(max_length=80)),
                ('data_inicio', models.DateField()),
            ],
        ),
    ]
