# Generated by Django 5.0.7 on 2024-07-24 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cidades', '0001_initial'),
        ('estados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('cnpj', models.CharField(db_column='CNPJ', max_length=80)),
                ('ie', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('endereco', models.CharField(max_length=80)),
                ('fone', models.CharField(max_length=30)),
                ('responsavel', models.CharField(max_length=80)),
                ('data_cadastro', models.DateField()),
                ('fk_cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cidades.cidade')),
                ('fk_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estados.estado')),
            ],
        ),
    ]
